### ISSUE TITLE
Pointer to sample code for Java

### ISSUE THREAD

**Issue by nikolay-g** [IBM-Cloud/compose-mongodb-helloworld-nodejs#4]
Great example!

Do you know how to do this in Spring Boot? Alternatively, can you point me to any Java code which runs on Bluemix and connects to Compose for Mongo?

**Comment by drpalaric** [comment]
There isn't a plan at the moment to have a Spring Boot Example. It's possible that we may have one for IBM Cloud Databases for MongoDB, however. But we haven't written an example at this point.
