### ISSUE TITLE
 connect compose mongodb from ibmbluemix

### ISSUE THREAD

**Issue by ManojKuppaiahSudhakara** [IBM-Cloud/compose-mongodb-helloworld-nodejs#8]
@codepope Hi, I am not able to connect Compose Mongodb using ibm bluemix. Can you please tell me how to connect compose mongodb from ibm bluemix. I tried using this connection but I am getting error like Credentials are not defined
`const util = require('util');
const assert = require('assert');
var cfenv = require('cfenv');
var appenv = cfenv.getAppEnv();
var services = appenv.services;
var mongodb_services = services["compose-for-mongodb"];
var ca = [new Buffer(credentials.ca_certificate_base64, 'base64')];
var mongodb;
MongoClient.connect(credentials.uri, {
        mongos: {
            ssl: true,
            sslValidate: true,
            sslCA: ca,
            poolSize: 1,
            reconnectTries: 1
        }
    },
    function(err, db) {
        // Here we handle the async response. This is a simple example and
        // we're not going to inject the database connection into the
        // middleware, just save it in a global variable, as long as there
        // isn't an error.
        if (err) {
            console.log(err);
        } else {
            // Although we have a connection, it's to the "admin" database
            // of MongoDB deployment. In this example, we want the
            // "examples" database so what we do here is create that
            // connection using the current connection.
            mongodb = db.db("IBMBLUEMIX");
        }
    }
);
`

**Comment by codepope** [comment]
Have you followed the instructions in the readme file?

https://github.com/IBM-Bluemix/compose-mongodb-helloworld-nodejs/blob/master/README.md

**Comment by ManojKuppaiahSudhakara** [comment]
@codepope I followed this and I bounded compose Mongodb in bluemix itself, From local machine I tried with this it uploading into compose mongodb I want to upload from bluemix`MongoClient.connect('mongodb://admin:password@gcp-us-east1-cpu.2.dblayer.com:17516,gcp-us-east1-cpu.3.dblayer.com:17516/IBMBLUEMIX?ssl=true', function(err, database) {
  //if (err) return console.log(err);
  //db = database;

//});`

**Comment by drpalaric** [comment]
Old issue.
